name: ws-env
channels:
- conda-forge
dependencies:
- python>=3.7.7, <3.12
- numpy
- scikit-learn
- ipython
- setuptools
- pandas>=1.2.5
- matplotlib
- black>=24.1.1
- pytest
- ipykernel
- pip
- pip:
  - plotly-express
  - tensorflowjs
  - tensorflow==2.15.0
  - tensorflow_decision_forests==1.8.1
